language: python
python:
  - "2.7"
  - "3.6"

env:
  - GLPK_VERSION=4.57 # ubuntu 16.04
  - GLPK_VERSION=4.61 # debian stable, fedora 28
  - GLPK_VERSION=4.65 # ubuntu 18.04, macOS (homebrew)

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgmp3-dev
  - wget http://ftp.gnu.org/gnu/glpk/glpk-${GLPK_VERSION}.tar.gz
  - tar xzf glpk-${GLPK_VERSION}.tar.gz
  - pushd glpk-${GLPK_VERSION} && ./configure --prefix=/usr && make && sudo make install && popd

install:
  - pip install tox-travis

script:
  - tox -v

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications:
  email:
    on_success: never
    on_failure: always
